language: python

arch:
  - arm64

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - "pip install -e .[st7789,bme680]"
  - "pip install flake8"
  - "pip install black"

script:
  - black --check pi_weatherstation/.
  - flake8 --exit-zero --statistics pi_weatherstation/.

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.9"
