global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    origin_prometheus: weather

remote_write:
- url: https://prometheus-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: <grafana-net prometheus username>
    password: <grafana-net prometheus password>

scrape_configs:
  - job_name: 'weather'
    static_configs:
    - targets:
        - 127.0.0.1:9191
